project-board:
  name: 'Pipeline for QA'
  review-column-name: 'REVIEW'
  test-column-name: 'TO TEST'

bounty-project-board:
  name: 'Status SOB Swarm'
  awaiting-approval-column-name: 'bounty-awaiting-approval'

welcome-bot:
  message: 'Thanks for making your first PR here!'

slack:
  notification:
    room: 'status-probot'